@echo off
choco install powershell
choco install Firefox
choco install thunderbird
choco install chromium
choco install skype
choco install foobar2000
choco install 7zip.install
choco install sumatrapdf.install
choco install ccleaner
choco install ccenhancer
choco install audacity
choco install flashplayerplugin
choco install filezilla
choco install irfanview
choco install mingw
choco install cygwin
choco install python2
choco install ruby
choco install hexchat
choco install gimp
choco install lightshot
choco install nmap
choco install openvpn
choco install mp3tag
choco install notepadplusplus.install
choco install wget
choco install wincdemu
choco install windirstat
choco install winpcap
choco install youtube-dl
choco install githubforwindows
choco install qbittorrent
choco install optipng
