@echo off
wget http://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-latest-win64-static.7z -t 0 -c
title Extracting...
7z e ffmpeg-latest-win64-static.7z -y -o".\cont"
title Deleting archive...
del ffmpeg-latest-win64-static.7z
title Copying...
xcopy .\cont\*.exe .\ /R /Y
title Cleaning up...
rmdir /S /Q .\cont
title Done! ffmpeg
pause
